[build]
functions = "netlify/functions"
publish = "dist"  # or "build", depending on your frontend tool (Vite, React, etc.)

[dev]
functions = "netlify/functions"

[functions]
included_files = ["netlify/functions/templates/*.html"]
